@startuml "Architecture"

!include <C4/C4_Component>

!theme reddress-darkblue
' !theme plain
' !theme metal
' !theme materia

' left to right direction

System_Ext(ca, "Custom assertions", "user can add own assertions")
System_Ext(cta, "Custom TestAdapter", "user can plug in custom test adapter to throw framework exception types")

System_Boundary(Is, "Is") {
    Component(ex, "NotException", "Custom exception", "uses call stack to append exact line of user code")
    Component(conf, "Configuration", "Global settings", "control behaviour of core components and assertions")

    System_Boundary(Assertions, "Assertions") {
        Component(ext, "Extension methods", "Public assertions", "actual implementation of different assertions")
        }

    System_Boundary(Core, "Core") {
        Component(ass, "Assertion", "Passed / Failed", "single entry point for failure behaviour")
        Component(check, "Check", "That / (Yields) / Unless", "fluent API to simplify condition check and error message creation")
        Component(ctx, "AssertionContext", "Assertion scope", "collects (failed) assertions without throwing on first")
        Component(ita, "ITestAdapter", "Report Failure(s)", "reports success and failure(s) to throw exceptions")
        }
    }
}

Rel(ass, ita, "reports failure to")
Rel(ctx, ex, "collects")
Rel(ita, ex, "throws")
Rel_R(cta, ita, "implements")

Rel_U(ext, check, "uses")
Rel(ext, ass, "pass / fail")
Rel_L(ca, check, "uses")

Rel_L(ctx, ita, "reports failures to")

Rel(check, ass, "pass / fail")
Rel(ass, ctx, "adds successes / failures")

Rel_R(conf, ass, "configures")
Rel(conf, ita, "configures")
Rel_U(conf, ext, "configures")


@enduml